# Generated by Django 2.2.2 on 2019-08-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phonenumber', models.BigIntegerField(verbose_name='phonenumber')),
                ('message', models.TextField(max_length=450)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
